baseURL = "http://blog.felfele.com"
languageCode = "en-us"
title = "Felfele Foundation"
theme = "hugo-theme-casper"
publishDir = "docs"
canonifyurls = true

[params]
  description = "Welcome to our blog"
  cover = "/images/stars.jpg"
  author = "Mark Vujevits"
  authorlocation = "Budapest, Hungary"
  RSSLink = "https://blog.felfele.com/index.xml"
